Metrics/LineLength:
  Max: 132 # good for desktop Github

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

AllCops:
  Exclude:
    - Gemfile
    - vendor/**/*
