development: &default
  url: <%= ENV['ELASTICSEARCH_URL'] || 'http://localhost:9200' %>
  index: <%= ENV['ELASTICSEARCH_INDEX'] || 'gravity' %>
  username: <%= ENV['ELASTICSEARCH_USERNAME'] || 'replace' %>
  password: <%= ENV['ELASTICSEARCH_PASSWORD'] || 'replace' %>
test:
  <<: *default
production:
  <<: *default
